version: '3'
services:
        mongodb:
                image: "mongo:latest"
                ports:
                        - "27017:27017"
                volumes:
                        - /home/fox/projects/lomonosov/data:/data/db
        mongoexpress:
                image: "mongo-express:latest"
                ports:
                        - "8081:8081"
                links:
                        - mongodb:mongo

